name: Build conda nightly
on:
  push:
    branches:
      - main
      - datafusion-sql-planner
  pull_request:
    paths:
      - setup.py
      - dask_planner/Cargo.toml
      - dask_planner/Cargo.lock
      - dask_planner/pyproject.toml
      - dask_planner/rust-toolchain.toml
      - continuous_integration/recipe/**
      - .github/workflows/conda.yml
  schedule:
    - cron: '0 0 * * 0'

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: conda-${{ github.head_ref }}
  cancel-in-progress: true

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  conda:
    name: Build (and optionally upload) the conda nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: "3.8"
          channel-priority: strict
      - name: Install dependencies
        run: |
          mamba install boa conda-verify

          which python
          pip list
          mamba list
      - name: Build conda packages
        run: |
          # suffix for nightly package versions
          export VERSION_SUFFIX=a`date +%y%m%d`

          conda mambabuild continuous_integration/recipe \
                           --no-anaconda-upload \
                           --no-test \
                           --output-folder nightlies
      - name: Test conda packages
        run: |
          conda mambabuild --test linux-64/*.tar.bz2
      - name: Upload linux-64 conda packages as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conda nightlies for linux-64
          path: linux-64/*.tar.bz2
      - name: Upload linux-aarch64 conda packages as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conda nightlies for linux-aarch64
          path: linux-aarch64/*.tar.bz2
      - name: Upload conda packages to Anaconda
        if: |
          github.event_name == 'push'
          && github.repository == 'dask-contrib/dask-sql'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.DASK_CONDA_TOKEN }}
        run: |
          # install anaconda for upload
          mamba install anaconda-client

          anaconda upload --label dev linux-64/*.tar.bz2
          anaconda upload --label dev linux-aarch64/*.tar.bz2
